repos:
  - repo: local
    hooks:
      - id: create-requirements
        name: create-requirements
        entry: "./requirements/create-requirements.sh"
        language: system
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: test-dags
        name: test-dags
        entry: "./tests/run-tests.sh"
        language: system
        always_run: true
        pass_filenames: false