name: Prod_CD

# Controls when the workflow will run

on:
  # Triggers the workflow on push or pull request events. Ignores if push/PR to main branch to prevent recursion
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ssh-and-pull:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.repository == 'is3107/airflow_dags'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs SSH commands
      - name: SSH into Prod VM and git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /home/is3107/airflow/dags
            git pull origin main
        
